name: CI

on: [push, pull_request]

jobs:

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [7,8,9,10] # Version of GFortran we want to use.
        python-version: [3.9]
    env:
      FC: gfortran-${{matrix.gcc_v}}
      GCC_V: ${{matrix.gcc_v}}

    steps:

    - name: Set vars
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup cmake
      if: contains( matrix.gcc_v, 9 )
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.19.x'

    - name: Install GFortran Linux
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-${GCC_V} gfortran-${GCC_V}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}
    - name: Compile_with_cmake
      # CMake build with unit tests, no documentation, with coverage analysis
      # No unicode so that coverage combined with the build script will cover unicode
      # and non-unicode code paths
      if: matrix.gcc_v == 9
      run: |
        GFORTRAN=gfortran-${{matrix.gcc_v}}
        GCOV=gcov-${{matrix.gcc_v}}
        mkdir cmake-build
        cd cmake-build
        cmake ..
        make -j 4 check
